'use client';

import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    applicationTitle: 'Gov Social Support',
    step: 'Step',
    of: 'of',
    next: 'Next',
    previous: 'Previous',
    submit: 'Submit Application',
    saving: 'Saving...',
    submitting: 'Submitting...',
    applicationSubmitted: 'Application Submitted Successfully!',
    applicationNumber: 'Your application number is',
    error: 'An error occurred. Please try again.',
    helpMeWrite: 'Help Me Write',
    aiSuggestion: 'AI Suggestion',
    accept: 'Accept',
    edit: 'Edit',
    discard: 'Discard',
    required: 'This field is required',
    invalidEmail: 'Invalid email address',
    invalidPhone: 'Invalid phone number',
    provideBasicInfo: 'Please provide your basic information',
    completeInSteps: 'Finish your application in a few steps',
    helpMeWrite: 'Help Me Write',
    tutorial: 'Tutorial',
    
    // Tooltips
    nationalIdTooltip: 'Enter your national ID number as shown on your official identification document',
    phoneTooltip: 'Include your country code (e.g., +971 for UAE). This will be used for important updates about your application',
    emailTooltip: 'Provide a valid email address. You will receive confirmation and status updates via email',
    dateOfBirthTooltip: 'Select your date of birth. This information is used to verify your eligibility for age-specific programs',
    genderTooltip: 'Select your gender as shown on your official documents',
    addressTooltip: 'Provide your complete residential address including building number, street name, and area',
    aiAssistTooltip: 'AI will help expand and professionalize your text for the application',
    aiAssistDisabledTooltip: 'Write at least 10 characters to enable AI assistance',
    
    // Step 1
    personalInformation: 'My Info',
    personalInformationFull: 'Personal Information',
    name: 'Full Name',
    nationalId: 'National ID',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    address: 'Address',
    city: 'City',
    state: 'State',
    country: 'Country',
    phone: 'Phone Number',
    email: 'Email Address',
    
    // Step 2
    familyFinancialInfo: 'Family & Finance',
    familyFinancialInfoFull: 'Family & Financial Details',
    maritalStatus: 'Marital Status',
    single: 'Single',
    married: 'Married',
    divorced: 'Divorced',
    widowed: 'Widowed',
    dependents: 'Number of Dependents',
    employmentStatus: 'Employment Status',
    employed: 'Employed',
    unemployed: 'Unemployed',
    selfEmployed: 'Self-Employed',
    retired: 'Retired',
    monthlyIncome: 'Monthly Income',
    housingStatus: 'Housing Status',
    owned: 'Owned',
    rented: 'Rented',
    withFamily: 'Living with Family',
    
    // Step 3
    situationDescriptions: 'My Situation',
    situationDescriptionsFull: 'Situation Description',
    currentSituation: 'Current Financial Situation',
    currentSituationPlaceholder: 'Describe your current financial situation and challenges...',
    employmentCircumstances: 'Employment Circumstances',
    employmentCircumstancesPlaceholder: 'Explain your employment situation and any obstacles...',
    reasonForApplying: 'Reason for Applying',
    reasonForApplyingPlaceholder: 'Explain why you are applying for social support...',
    
    // Step 4
    reviewAndSubmit: 'Review & Send',
    reviewAndSubmitFull: 'Review and Submit',
    reviewYourInfo: 'Please review your information carefully before submitting',
    readyToSubmit: 'Ready to Submit?',
    submitWarning: 'Please ensure all information is correct as changes cannot be made after submission.',
    submitApplication: 'Submit Application',

    // Email submission phases
    submittingApplication: 'Submitting Application',
    processingInfo: 'Processing your information...',
    sendingConfirmation: 'Sending Confirmation',
    sendingToEmail: 'Sending confirmation to your email...',
    emailSentSuccess: 'Email Sent Successfully!',
    confirmationSent: 'Confirmation has been sent to your inbox',
    applicationSubmittedSuccess: 'Application Submitted Successfully!',
    applicationSuccessDesc: 'Your application has been successfully submitted.',
    sendingTo: 'Sending to:',

    // Onboarding tour
    tourWelcomeTitle: 'Welcome to Social Support Portal',
    tourWelcomeDesc: 'Let us guide you through the application process. It only takes a few minutes!',
    tourPersonalTitle: 'My Information',
    tourPersonalDesc: 'First, we\'ll collect your basic information like name, ID, and contact details. All information is kept secure and confidential.',
    tourPersonalTip1: 'Have your National ID ready',
    tourPersonalTip2: 'Ensure your contact info is up-to-date',
    tourPersonalTip3: 'Double-check your email address',
    tourFamilyTitle: 'Family & Financial Details',
    tourFamilyDesc: 'Next, we\'ll ask about your family situation and financial status to better understand your needs.',
    tourFamilyTip1: 'Know your monthly income',
    tourFamilyTip2: 'Count all dependents',
    tourFamilyTip3: 'Include all sources of support',
    tourSituationTitle: 'Your Situation',
    tourSituationDesc: 'Here you\'ll describe your current situation and why you\'re applying. Be detailed and honest - this helps us serve you better.',
    tourSituationTip1: 'Be specific about your challenges',
    tourSituationTip2: 'Explain your employment situation',
    tourSituationTip3: 'Use the AI assistant for help writing',
    tourReviewTitle: 'Review & Submit',
    tourReviewDesc: 'Finally, you\'ll review all your information before submitting. You can edit any section if needed.',
    tourReviewTip1: 'Review everything carefully',
    tourReviewTip2: 'Edit any mistakes before submitting',
    tourReviewTip3: 'Save your application number',
    tourReadyTitle: 'You\'re All Set!',
    tourReadyDesc: 'You now know everything needed to complete your application. Good luck!',
    quickTips: 'Quick Tips',
    skipTour: 'Skip Tour',
    startApplication: 'Start Application',

    // App Details Page
    caseStudy: 'Case Study Implementation',
    appDetailsTitle: 'Social Support Portal with AI Assistance',
    appDetailsSubtitle: 'A modern, accessible government portal featuring AI-powered writing assistance, comprehensive testing, and bilingual support.',
    viewApp: 'View Live App',
    viewCode: 'View Source Code',
    requirementsFulfilled: 'Requirements Fulfilled',
    requirementsFulfilledDesc: 'All original case study requirements have been implemented with additional enhancements.',

    reqMultiStep: '4-Step Form Wizard',
    reqMultiStepDesc: 'Enhanced from 3-step to 4-step process with review functionality',
    reqAI: 'OpenAI GPT Integration',
    reqAIDesc: 'Context-aware writing assistance for application text fields',
    reqResponsive: 'Responsive Design',
    reqResponsiveDesc: 'Mobile-first approach supporting all device sizes',
    reqAccessibility: 'Accessibility Features',
    reqAccessibilityDesc: 'WCAG compliant with keyboard navigation and screen reader support',
    enhanced: 'Enhanced',

    keyFeatures: 'Key Features',
    keyFeaturesDesc: 'Core functionality that makes the application user-friendly and efficient.',
    featureAI: 'AI Writing Assistant',
    featureAIDesc: 'Smart suggestions for professional application content',
    featureProgress: 'Progress Tracking',
    featureProgressDesc: 'Visual progress bar with clickable navigation between steps',
    featureBilingual: 'Bilingual Support',
    featureBilingualDesc: 'Complete English and Arabic interface with RTL layout',
    featureAutoSave: 'Auto-Save Progress',
    featureAutoSaveDesc: 'Automatic progress saving with localStorage persistence',
    featureEmail: 'Email Confirmation',
    featureEmailDesc: 'Professional email confirmation simulation flow',
    featureOnboarding: 'Interactive Tour',
    featureOnboardingDesc: '6-step guided onboarding for new users',

    technicalExcellence: 'Technical Excellence',
    technicalExcellenceDesc: 'Built with modern technologies and best practices for reliability and performance.',
    modernTechStack: 'Modern Tech Stack',
    qualityAssurance: 'Quality Assurance',
    comprehensiveTesting: '17 comprehensive test cases',
    accessibilityCompliance: 'WCAG 2.1 AA compliance',
    performanceOptimized: 'Performance optimized',
    securityFirst: 'Security-first approach',

    projectStructure: 'Project Structure',
    projectStructureDesc: 'Visual overview of the application architecture and component organization.',
    projectStructureDiagram: 'Project Structure Diagram',
    beyondRequirements: 'Beyond Requirements',
    beyondRequirementsDesc: 'Additional features that enhance the user experience and demonstrate technical excellence.',
    bonusOnboarding: 'Interactive onboarding tour system',
    bonusEmail: 'Multi-phase email confirmation flow',
    bonusCelebration: 'Celebration animations for positive feedback',
    bonusTheme: 'Professional dark theme design',
    bonusRTL: 'Complete Arabic RTL layout support',
    bonusTesting: 'Comprehensive Jest testing suite',

    readyToExplore: 'Ready to Explore?',
    readyToExploreDesc: 'Experience the live application or explore the source code to see the implementation details.',
    tryApplication: 'Try the Application',
    viewSource: 'View Source Code',
    builtWith: 'Built with',
    forAccessibleGovernment: 'for accessible government services',
  },
  ar: {
    applicationTitle: 'طلب الدعم الاجتماعي',
    step: 'الخطوة',
    of: 'من',
    next: 'التالي',
    previous: 'السابق',
    submit: 'إرسال الطلب',
    saving: 'جاري الحفظ...',
    submitting: 'جاري الإرسال...',
    applicationSubmitted: 'تم إرسال الطلب بنجاح!',
    applicationNumber: 'رقم طلبك هو',
    error: 'حدث خطأ. يرجى المحاولة مرة أخرى.',
    helpMeWrite: 'ساعدني في الكتابة',
    aiSuggestion: 'اقتراح الذكاء الاصطناعي',
    accept: 'قبول',
    edit: 'تعديل',
    discard: 'رفض',
    required: 'هذا الحقل مطلوب',
    invalidEmail: 'عنوان البريد الإلكتروني غير صالح',
    invalidPhone: 'رقم الهاتف غير صالح',
    provideBasicInfo: 'يرجى تقديم معلوماتك الأساسية',
    completeInSteps: 'أكمل طلبك في خطوات بسيطة',
    helpMeWrite: 'ساعدني في الكتابة',
    tutorial: 'دليل الاستخدام',
    
    // Tooltips
    nationalIdTooltip: 'أدخل رقم الهوية الوطنية كما يظهر في وثائق هويتك الرسمية',
    phoneTooltip: 'أدخل رمز الدولة (مثال: +971 للإمارات). سيتم استخدام هذا الرقم لإرسال تحديثات مهمة حول طلبك',
    emailTooltip: 'قدم عنوان بريد إلكتروني صحيح. ستتلقى تأكيدات وتحديثات الحالة عبر البريد الإلكتروني',
    dateOfBirthTooltip: 'اختر تاريخ ميلادك. تستخدم هذه المعلومة للتحقق من أهليتك للبرامج المخصصة لفئات عمرية محددة',
    genderTooltip: 'اختر جنسك كما يظهر في وثائقك الرسمية',
    addressTooltip: 'قدم عنوانك السكني الكامل بما في ذلك رقم المبنى واسم الشارع والمنطقة',
    aiAssistTooltip: 'سيساعدك الذكاء الاصطناعي في توسيع وتطوير نصك للطلب بشكل مهني',
    aiAssistDisabledTooltip: 'اكتب 10 أحرف على الأقل لتفعيل مساعد الذكاء الاصطناعي',
    
    // Step 1
    personalInformation: 'معلوماتي',
    personalInformationFull: 'المعلومات الشخصية',
    name: 'الاسم الكامل',
    nationalId: 'الهوية الوطنية',
    dateOfBirth: 'تاريخ الميلاد',
    gender: 'النوع',
    male: 'ذكر',
    female: 'أنثى',
    address: 'العنوان',
    city: 'المدينة',
    state: 'المحافظة',
    country: 'الدولة',
    phone: 'رقم الهاتف',
    email: 'البريد الإلكتروني',
    
    // Step 2
    familyFinancialInfo: 'الأسرة و الماليات',
    familyFinancialInfoFull: 'تفاصيل الأسرة والمالية',
    maritalStatus: 'الحالة الاجتماعية',
    single: 'أعزب',
    married: 'متزوج',
    divorced: 'مطلق',
    widowed: 'أرمل',
    dependents: 'عدد المعالين',
    employmentStatus: 'حالة التوظيف',
    employed: 'موظف',
    unemployed: 'عاطل عن العمل',
    selfEmployed: 'عمل حر',
    retired: 'متقاعد',
    monthlyIncome: 'الدخل الشهري',
    housingStatus: 'وضع السكن',
    owned: 'ملك',
    rented: 'إيجار',
    withFamily: 'مع العائلة',
    
    // Step 3
    situationDescriptions: 'وصف الحالة',
    situationDescriptionsFull: 'وصف الحالة التفصيلي',
    currentSituation: 'الوضع المالي الحالي',
    currentSituationPlaceholder: 'صف وضعك المالي الحالي والتحديات التي تواجهها...',
    employmentCircumstances: 'ظروف العمل',
    employmentCircumstancesPlaceholder: 'اشرح وضعك الوظيفي وأي عقبات تواجهها...',
    reasonForApplying: 'سبب التقديم',
    reasonForApplyingPlaceholder: 'اشرح سبب تقديمك للحصول على الدعم الاجتماعي...',
    
    // Step 4
    reviewAndSubmit: 'مراجعة وإرسال',
    reviewAndSubmitFull: 'المراجعة والإرسال',
    reviewYourInfo: 'يرجى مراجعة معلوماتك بعناية قبل الإرسال',
    readyToSubmit: 'جاهز للإرسال؟',
    submitWarning: 'يرجى التأكد من صحة جميع المعلومات حيث لا يمكن إجراء تغييرات بعد الإرسال.',
    submitApplication: 'إرسال الطلب',

    // Email submission phases
    submittingApplication: 'جاري إرسال الطلب',
    processingInfo: 'جاري معالجة معلوماتك...',
    sendingConfirmation: 'جاري إرسال التأكيد',
    sendingToEmail: 'جاري إرسال التأكيد إلى بريدك الإلكتروني...',
    emailSentSuccess: 'تم إرسال البريد الإلكتروني بنجاح!',
    confirmationSent: 'تم إرسال التأكيد إلى صندوق الوارد الخاص بك',
    applicationSubmittedSuccess: 'تم إرسال الطلب بنجاح!',
    applicationSuccessDesc: 'تم إرسال طلبك بنجاح.',
    sendingTo: 'إرسال إلى:',

    // Onboarding tour
    tourWelcomeTitle: 'مرحباً ببوابة الدعم الاجتماعي',
    tourWelcomeDesc: 'دعنا نرشدك خلال عملية التقديم. الأمر لا يستغرق سوى دقائق قليلة!',
    tourPersonalTitle: 'المعلومات الشخصية',
    tourPersonalDesc: 'أولاً، سنجمع معلوماتك الأساسية مثل الاسم والهوية وتفاصيل الاتصال. جميع المعلومات محفوظة بسرية وأمان.',
    tourPersonalTip1: 'احضر الهوية الوطنية',
    tourPersonalTip2: 'تأكد من صحة معلومات الاتصال',
    tourPersonalTip3: 'راجع عنوان البريد الإلكتروني',
    tourFamilyTitle: 'تفاصيل الأسرة والمالية',
    tourFamilyDesc: 'بعد ذلك، سنسأل عن وضع أسرتك والحالة المالية لفهم احتياجاتك بشكل أفضل.',
    tourFamilyTip1: 'اعرف دخلك الشهري',
    tourFamilyTip2: 'احسب جميع المعالين',
    tourFamilyTip3: 'أضف جميع مصادر الدعم',
    tourSituationTitle: 'حالتك',
    tourSituationDesc: 'هنا ستصف حالتك الحالية وسبب التقديم. كن مفصلاً وصادقاً - هذا يساعدنا على خدمتك بشكل أفضل.',
    tourSituationTip1: 'كن محدداً حول تحدياتك',
    tourSituationTip2: 'اشرح وضعك الوظيفي',
    tourSituationTip3: 'استخدم مساعد الذكاء الاصطناعي للمساعدة في الكتابة',
    tourReviewTitle: 'مراجعة وإرسال',
    tourReviewDesc: 'أخيراً، ستراجع جميع معلوماتك قبل الإرسال. يمكنك تعديل أي قسم إذا لزم الأمر.',
    tourReviewTip1: 'راجع كل شيء بعناية',
    tourReviewTip2: 'عدل أي أخطاء قبل الإرسال',
    tourReviewTip3: 'احفظ رقم طلبك',
    tourReadyTitle: 'أنت جاهز!',
    tourReadyDesc: 'تعرف الآن كل ما تحتاجه لإكمال طلبك. حظاً موفقاً!',
    quickTips: 'نصائح سريعة',
    skipTour: 'تخطي الجولة',
    startApplication: 'بدء الطلب',

    // App Details Page
    caseStudy: 'تطبيق دراسة الحالة',
    appDetailsTitle: 'بوابة الدعم الاجتماعي مع المساعد الذكي',
    appDetailsSubtitle: 'بوابة حكومية حديثة ومتاحة تتميز بمساعد الكتابة المدعوم بالذكاء الاصطناعي واختبارات شاملة ودعم ثنائي اللغة.',
    viewApp: 'عرض التطبيق',
    viewCode: 'عرض الكود المصدري',
    requirementsFulfilled: 'المتطلبات المُحققة',
    requirementsFulfilledDesc: 'تم تنفيذ جميع متطلبات دراسة الحالة الأصلية مع تحسينات إضافية.',

    reqMultiStep: 'نموذج من 4 خطوات',
    reqMultiStepDesc: 'محسن من 3 خطوات إلى 4 خطوات مع وظائف المراجعة',
    reqAI: 'تكامل OpenAI GPT',
    reqAIDesc: 'مساعد الكتابة الذكي لحقول النص في الطلب',
    reqResponsive: 'تصميم متجاوب',
    reqResponsiveDesc: 'مقاربة الهاتف المحمول أولاً تدعم جميع أحجام الأجهزة',
    reqAccessibility: 'ميزات إمكانية الوصول',
    reqAccessibilityDesc: 'متوافق مع WCAG مع التنقل بلوحة المفاتيح ودعم قارئ الشاشة',
    enhanced: 'محسن',

    keyFeatures: 'الميزات الرئيسية',
    keyFeaturesDesc: 'الوظائف الأساسية التي تجعل التطبيق سهل الاستخدام وفعال.',
    featureAI: 'مساعد الكتابة الذكي',
    featureAIDesc: 'اقتراحات ذكية لمحتوى الطلب المهني',
    featureProgress: 'تتبع التقدم',
    featureProgressDesc: 'شريط تقدم مرئي مع إمكانية التنقل بين الخطوات',
    featureBilingual: 'دعم ثنائي اللغة',
    featureBilingualDesc: 'واجهة كاملة باللغتين الإنجليزية والعربية مع تخطيط RTL',
    featureAutoSave: 'حفظ تلقائي للتقدم',
    featureAutoSaveDesc: 'حفظ التقدم تلقائياً مع استمرارية localStorage',
    featureEmail: 'تأكيد البريد الإلكتروني',
    featureEmailDesc: 'تدفق محاكاة تأكيد البريد الإلكتروني المهني',
    featureOnboarding: 'جولة تفاعلية',
    featureOnboardingDesc: 'جولة إرشادية من 6 خطوات للمستخدمين الجدد',

    technicalExcellence: 'التميز التقني',
    technicalExcellenceDesc: 'مبني بالتقنيات الحديثة وأفضل الممارسات للموثوقية والأداء.',
    modernTechStack: 'أحدث التقنيات',
    qualityAssurance: 'ضمان الجودة',
    comprehensiveTesting: '17 حالة اختبار شاملة',
    accessibilityCompliance: 'توافق WCAG 2.1 AA',
    performanceOptimized: 'محسن الأداء',
    securityFirst: 'مقاربة الأمان أولاً',

    projectStructure: 'هيكل المشروع',
    projectStructureDesc: 'نظرة بصرية شاملة على هندسة التطبيق وتنظيم المكونات.',
    projectStructureDiagram: 'مخطط هيكل المشروع',
    beyondRequirements: 'ما وراء المتطلبات',
    beyondRequirementsDesc: 'ميزات إضافية تحسن تجربة المستخدم وتُظهر التميز التقني.',
    bonusOnboarding: 'نظام جولة إرشادية تفاعلية',
    bonusEmail: 'تدفق تأكيد البريد الإلكتروني متعدد المراحل',
    bonusCelebration: 'رسوم متحركة احتفالية للتغذية الراجعة الإيجابية',
    bonusTheme: 'تصميم موضوع مظلم مهني',
    bonusRTL: 'دعم كامل لتخطيط RTL العربي',
    bonusTesting: 'مجموعة اختبارات Jest شاملة',

    readyToExplore: 'مستعد للاستكشاف؟',
    readyToExploreDesc: 'جرب التطبيق المباشر أو استكشف الكود المصدري لرؤية تفاصيل التنفيذ.',
    tryApplication: 'جرب التطبيق',
    viewSource: 'عرض الكود المصدري',
    builtWith: 'مبني بـ',
    forAccessibleGovernment: 'للخدمات الحكومية المتاحة',
  }
};

export const LanguageProvider = ({ children, lang }) => {
  const language = lang || 'en';

  const t = (key) => {
    if (!translations[language]) {
      console.warn(`Language ${language} not found, falling back to 'en'`);
      return translations['en'][key] || key;
    }
    return translations[language][key] || key;
  };

  const value = {
    language,
    t,
    isRTL: language === 'ar'
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};