'use client';

import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    applicationTitle: 'Gov Social Support',
    step: 'Step',
    of: 'of',
    next: 'Next',
    previous: 'Previous',
    submit: 'Submit Application',
    clickToGoBack: 'Go back & Edit',
    saving: 'Saving...',
    submitting: 'Submitting...',
    applicationSubmitted: 'Application Submitted Successfully!',
    applicationNumber: 'Your application number is',
    error: 'An error occurred. Please try again.',
    helpMeWrite: 'Help Me Write',
    aiSuggestion: 'AI Suggestion',
    accept: 'Accept',
    edit: 'Edit',
    discard: 'Discard',

    // AI Assistant Modal
    craftingContent: 'Crafting professional content...',
    professionalContentSuggestion: 'Professional Content Suggestion',
    craftedContentDesc: 'We\'ve crafted professional and compelling content for your application:',
    editTextHere: 'Edit your text here...',
    editingTextDesc: 'Edit the text, with options to regenerate, save, and apply your updates.',
    cancel: 'Cancel',
    regenerate: 'Regenerate',
    useEditedText: 'Use your edited text as new input to AI',
    regenerateSameRequest: 'Regenerate same request',
    saveEdits: 'Save edits and apply to form',
    editText: 'Edit text',
    saveAndApply: 'Save & Apply',
    applyToForm: 'Apply text to form',
    applyText: 'Apply Text',
    required: 'This field is required',
    invalidEmail: 'Invalid email address',
    invalidPhone: 'Invalid phone number',
    minCharacters: 'Please provide at least {{count}} characters',
    details: 'Details',
    documentation: 'Documentation',
    dateCannotBeFuture: 'Date cannot be in the future',
    invalidDateOfBirth: 'Please enter a valid date of birth',

    // Progress labels - Used in ModernProgressBar component
    progress: 'Progress',
    complete: 'Complete',

    // Error boundary labels
    formError: 'Form Error',
    formErrorDescription: 'There was an issue with the form. Your data has been preserved.',
    dataPreserved: 'Data Preserved',
    dataPreservedMessage: 'Your form data has been automatically saved and will be restored when you continue.',
    retryForm: 'Try Again',
    resetForm: 'Reset Form',
    provideBasicInfo: 'Please provide your basic information',
    completeInSteps: 'Finish your application in a few steps',
    helpMeWrite: 'Help Me Write',
    tutorial: 'Tutorial',
    
    // Tooltips
    nationalIdTooltip: 'Enter your national ID number as shown on your official identification document',
    phoneTooltip: 'Include your country code (e.g., +971 for UAE). This will be used for important updates about your application',
    emailTooltip: 'Provide a valid email address. You will receive confirmation and status updates via email',
    dateOfBirthTooltip: 'Select your date of birth. This information is used to verify your eligibility for age-specific programs',
    genderTooltip: 'Select your gender as shown on your official documents',
    addressTooltip: 'Provide your complete residential address including building number, street name, and area',
    aiAssistTooltip: 'AI will help expand and professionalize your text for the application',
    aiAssistDisabledTooltip: 'Write at least 10 characters to enable AI assistance',

    // Contextual AI tooltips for each field
    aiAssistCurrentSituation: 'Describe your main financial challenges and our smart AI will help you craft a clear, professional explanation that strengthens your application',
    aiAssistEmployment: 'Explain your work situation and our AI assistant will help you present your employment circumstances in the most effective way',
    aiAssistReasonApplying: 'Share why you need support and our intelligent writing assistant will help you articulate your reasons professionally and persuasively',

    aiAssistCurrentSituationDisabled: 'Start typing about your financial situation to unlock AI writing assistance',
    aiAssistEmploymentDisabled: 'Begin describing your employment situation to enable smart writing help',
    aiAssistReasonApplyingDisabled: 'Share your reasons for applying to activate AI writing support',
    
    // Step 1
    personalInformation: 'My Info',
    personalInformationFull: 'Personal Information',
    name: 'Full Name',
    nationalId: 'National ID',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    address: 'Address',
    city: 'City',
    state: 'State',
    country: 'Country',
    phone: 'Phone Number',
    email: 'Email Address',
    
    // Step 2
    familyFinancialInfo: 'Family & Finance',
    familyFinancialInfoFull: 'Family & Financial Details',
    maritalStatus: 'Marital Status',
    single: 'Single',
    married: 'Married',
    divorced: 'Divorced',
    widowed: 'Widowed',
    dependents: 'Number of Dependents',
    employmentStatus: 'Employment Status',
    employed: 'Employed',
    unemployed: 'Unemployed',
    selfEmployed: 'Self-Employed',
    retired: 'Retired',
    monthlyIncome: 'Monthly Income',
    housingStatus: 'Housing Status',
    owned: 'Owned',
    rented: 'Rented',
    withFamily: 'Living with Family',
    
    // Step 3
    situationDescriptions: 'My Situation',
    situationDescriptionsFull: 'Situation Description',
    currentSituation: 'Current Financial Situation',
    currentSituationPlaceholder: 'Describe your current financial situation and challenges...',
    employmentCircumstances: 'Employment Circumstances',
    employmentCircumstancesPlaceholder: 'Explain your employment situation and any obstacles...',
    reasonForApplying: 'Reason for Applying',
    reasonForApplyingPlaceholder: 'Explain why you are applying for social support...',
    
    // Step 4
    reviewAndSubmit: 'Review & Send',
    reviewAndSubmitFull: 'Review and Submit',
    reviewYourInfo: 'Please review your information carefully before submitting',
    readyToSubmit: 'Ready to Submit?',
    submitWarning: 'Please ensure all information is correct as changes cannot be made after submission.',
    submitApplication: 'Submit Application',

    // Email submission phases
    submittingApplication: 'Submitting Application',
    processingInfo: 'Processing your information...',
    sendingConfirmation: 'Sending Confirmation',
    sendingToEmail: 'Sending confirmation to your email...',
    emailSentSuccess: 'Email Sent Successfully!',
    confirmationSent: 'Confirmation has been sent to your inbox',
    applicationSubmittedSuccess: 'Application Submitted Successfully!',
    applicationSuccessDesc: 'You will receive an email confirmation shortly with next steps and contact information.',
    sendingTo: 'Sending to:',

    // Onboarding tour
    tourWelcomeTitle: 'Welcome to Social Support Portal',
    tourWelcomeDesc: 'Let us guide you through the application process. It only takes a few minutes!',
    tourPersonalTitle: 'My Information',
    tourPersonalDesc: 'First, we\'ll collect your basic information like name, ID, and contact details. All information is kept secure and confidential.',
    tourPersonalTip1: 'Have your National ID ready',
    tourPersonalTip2: 'Ensure your contact info is up-to-date',
    tourPersonalTip3: 'Double-check your email address',
    tourFamilyTitle: 'Family & Financial Details',
    tourFamilyDesc: 'Next, we\'ll ask about your family situation and financial status to better understand your needs.',
    tourFamilyTip1: 'Know your monthly income',
    tourFamilyTip2: 'Count all dependents',
    tourFamilyTip3: 'Include all sources of support',
    tourSituationTitle: 'Your Situation',
    tourSituationDesc: 'Here you\'ll describe your current situation and why you\'re applying. Be detailed and honest - this helps us serve you better.',
    tourSituationTip1: 'Be specific about your challenges',
    tourSituationTip2: 'Explain your employment situation',
    tourSituationTip3: 'Use the AI assistant for help writing',
    tourReviewTitle: 'Review & Submit',
    tourReviewDesc: 'Finally, you\'ll review all your information before submitting. You can edit any section if needed.',
    tourReviewTip1: 'Review everything carefully',
    tourReviewTip2: 'Edit any mistakes before submitting',
    tourReviewTip3: 'Save your application number',
    tourReadyTitle: 'You\'re All Set!',
    tourReadyDesc: 'You now know everything needed to complete your application. Good luck!',
    quickTips: 'Quick Tips',
    skipTour: 'Skip Tour',
    startApplication: 'Start Application',

    // App Details Page
    caseStudy: 'Case Study Implementation',
    caseStudyFor: 'Case Study Implementation for',
    caseStudyDocumentation: 'Documentation',
    northbaySolutions: 'Northbay Solutions',
    appDetailsTitle: 'Social Support Portal with AI Assistance',
    appDetailsSubtitle: 'A modern and accessible government services portal, featuring AI-powered writing assistance, robust test coverage, and full bilingual support in English and Arabic',
    viewApp: 'View Live App',
    viewCode: 'View Source Code',
    requirementsFulfilled: 'Requirements Fulfilled',
    requirementsFulfilledDesc: 'All original case study requirements have been implemented with additional enhancements.',

    reqMultiStep: '4-Step Form Wizard',
    reqMultiStepDesc: 'Enhanced from 3-step to 4-step process with review or easy edit before submit functionality',
    reqAI: 'OpenAI GPT Integration',
    reqAIDesc: 'Context-aware writing assistance for application text fields',
    reqResponsive: 'Responsive Design',
    reqResponsiveDesc: 'Mobile-first approach supporting all device sizes',
    reqAccessibility: 'Accessibility Features',
    reqAccessibilityDesc: 'WCAG compliant with keyboard navigation and screen reader support',
    enhanced: 'Enhanced',

    keyFeatures: 'Key Features',
    keyFeaturesDesc: 'Core functionality that makes the application user-friendly and efficient.',
    featureAI: 'AI Writing Assistant',
    featureAIDesc: 'Smart suggestions for professional application content',
    featureProgress: 'Progress Tracking',
    featureProgressDesc: 'Visual progress bar with clickable navigation between steps',
    featureBilingual: 'Bilingual Support',
    featureBilingualDesc: 'Complete English and Arabic interface with RTL layout',
    featureAutoSave: 'Auto-Save Progress',
    featureAutoSaveDesc: 'Automatic progress saving with localStorage persistence',
    featureEmail: 'Email Confirmation',
    featureEmailDesc: 'Professional email confirmation simulation flow',
    featureOnboarding: 'Interactive Tour',
    featureOnboardingDesc: '6-step guided onboarding for new users',

    technicalExcellence: 'Technical Excellence',
    technicalExcellenceDesc: 'Built with modern technologies and best practices for reliability and performance.',
    modernTechStack: 'Modern Tech Stack',
    qualityAssurance: 'Quality Assurance',
    comprehensiveTesting: '17 comprehensive test cases',
    accessibilityCompliance: 'WCAG 2.1 AA compliance',
    performanceOptimized: 'Performance optimized',
    securityFirst: 'Security-first approach',

    projectStructure: 'Project Structure',
    projectStructureDesc: 'Visual overview of the application architecture and component organization.',
    projectStructureDiagram: 'Project Structure Diagram',
    beyondRequirements: 'Beyond Requirements',
    beyondRequirementsDesc: 'Additional features that enhance the user experience and demonstrate technical excellence.',
    bonusOnboarding: 'Interactive onboarding tour system',
    bonusEmail: 'Multi-phase email confirmation flow',
    bonusCelebration: 'Celebration animations for positive feedback',
    bonusTheme: 'Professional dark theme design',
    bonusRTL: 'Complete Arabic RTL layout support',
    bonusTesting: 'Comprehensive Jest testing suite',

    readyToExplore: 'Ready to Explore?',
    readyToExploreDesc: 'Experience the live application or explore the source code to see the implementation details.',
    tryApplication: 'Try the Application',
    viewSource: 'View Source Code',
    builtWith: 'Built with',
    forAccessibleGovernment: 'for Northbay Solutions team',
  },
  ar: {
    applicationTitle: 'منصة الدعم الاجتماعي',
    step: 'الخطوة',
    of: 'من',
    next: 'التالي',
    previous: 'السابق',
    submit: 'تقديم الطلب',
    clickToGoBack: 'العودة والتعديل',
    saving: 'جاري الحفظ...',
    submitting: 'جاري التقديم...',
    applicationSubmitted: 'تم تقديم طلبك بنجاح',
    applicationNumber: 'رقم الطلب',
    error: 'حدث خطأ، يرجى إعادة المحاولة',
    helpMeWrite: 'مساعدة في الكتابة',
    aiSuggestion: 'اقتراح تلقائي',
    accept: 'موافق',
    edit: 'تعديل',
    discard: 'إلغاء',

    // AI Assistant Modal
    craftingContent: 'جاري صياغة محتوى احترافي...',
    professionalContentSuggestion: 'المحتوى الاحترافي المقترح',
    craftedContentDesc: 'قمنا بصياغة محتوى احترافي ومقنع لطلبك:',
    editTextHere: 'قم بتعديل النص هنا...',
    editingTextDesc: 'تحرير النص، مع خيارات لإعادة التوليد أو الحفظ أو تطبيق التحديثات.',
    cancel: 'إلغاء',
    regenerate: 'إعادة إنشاء',
    useEditedText: 'استخدم النص المعدل كمدخل جديد للذكاء الاصطناعي',
    regenerateSameRequest: 'إعادة إنشاء نفس الطلب',
    saveEdits: 'حفظ التعديلات وتطبيقها على النموذج',
    editText: 'تعديل النص',
    saveAndApply: 'حفظ وتطبيق',
    applyToForm: 'تطبيق النص على النموذج',
    applyText: 'تطبيق النص',
    required: 'مطلوب',
    invalidEmail: 'البريد الإلكتروني غير صحيح',
    invalidPhone: 'رقم الهاتف غير صحيح',
    minCharacters: 'يرجى كتابة {{count}} حرف على الأقل',
    details: 'التفاصيل',
    documentation: 'عن التطبيق',
    dateCannotBeFuture: 'لا يمكن أن يكون التاريخ في المستقبل',
    invalidDateOfBirth: 'يرجى إدخال تاريخ ميلاد صحيح',

    // Progress labels - Used in ModernProgressBar component
    progress: 'التقدم',
    complete: 'مكتمل',

    // Error boundary labels
    formError: 'خطأ في النموذج',
    formErrorDescription: 'حدث خطأ في النموذج. تم حفظ بياناتك بأمان.',
    dataPreserved: 'البيانات محفوظة',
    dataPreservedMessage: 'تم حفظ بيانات النموذج تلقائياً وسيتم استعادتها عند المتابعة.',
    retryForm: 'المحاولة مرة أخرى',
    resetForm: 'إعادة تعيين النموذج',
    provideBasicInfo: 'يرجى إدخال بياناتك الأساسية',
    completeInSteps: 'أكمل طلبك بخطوات بسيطة',
    helpMeWrite: 'مساعدة في الكتابة',
    tutorial: 'دليل الاستخدام',
    
    // Tooltips
    nationalIdTooltip: 'يرجى إدخال رقم الهوية الإماراتية كما يظهر في وثيقة الهوية الرسمية',
    phoneTooltip: 'يرجى إدخال رقم الهاتف المتحرك مع رمز الدولة (+971 للإمارات). سيتم استخدامه لإرسال تحديثات هامة حول طلبكم',
    emailTooltip: 'يرجى إدخال بريد إلكتروني صحيح. ستتلقون تأكيد الطلب وتحديثات الحالة عبر البريد الإلكتروني',
    dateOfBirthTooltip: 'يرجى اختيار تاريخ الميلاد. تستخدم هذه المعلومة للتحقق من الأهلية للبرامج المخصصة للفئات العمرية المختلفة',
    genderTooltip: 'يرجى اختيار الجنس كما يظهر في الوثائق الرسمية',
    addressTooltip: 'يرجى إدخال العنوان الوطني الكامل أو العنوان السكني مع تفاصيل المنطقة',
    aiAssistTooltip: 'ستساعدكم الأداة التلقائية في صياغة وتطوير وصف طلبكم بصورة مهنية',
    aiAssistDisabledTooltip: 'يرجى كتابة 10 أحرف على الأقل لتفعيل المساعدة التلقائية',

    // نصائح الذكاء الاصطناعي المخصصة لكل حقل
    aiAssistCurrentSituation: 'اشرحوا تحدياتكم المالية الأساسية وسيساعدكم مساعدنا الذكي في صياغة تفسير واضح ومهني يقوي طلبكم',
    aiAssistEmployment: 'وضحوا وضعكم الوظيفي وسيساعدكم المساعد الذكي في عرض ظروفكم المهنية بأفضل طريقة ممكنة',
    aiAssistReasonApplying: 'شاركونا أسباب حاجتكم للدعم وسيساعدكم المساعد الذكي في التعبير عن أسبابكم بشكل مهني ومقنع',

    aiAssistCurrentSituationDisabled: 'ابدؤوا بوصف وضعكم المالي لتفعيل المساعدة الذكية في الكتابة',
    aiAssistEmploymentDisabled: 'ابدؤوا بوصف وضعكم الوظيفي لتفعيل المساعدة الذكية في الكتابة',
    aiAssistReasonApplyingDisabled: 'شاركوا أسباب تقديمكم للطلب لتفعيل دعم الكتابة الذكي',
    
    // Step 1
    personalInformation: 'بياناتي',
    personalInformationFull: 'البيانات الشخصية',
    name: 'الاسم الكامل',
    nationalId: 'رقم الهوية',
    dateOfBirth: 'تاريخ الميلاد',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    address: 'العنوان الوطني',
    city: 'المدينة',
    state: 'المحافظة',
    country: 'الدولة',
    phone: 'رقم الهاتف المتحرك',
    email: 'البريد الإلكتروني',
    
    // Step 2
    familyFinancialInfo: 'بيانات الأسرة',
    familyFinancialInfoFull: 'بيانات الأسرة والوضع المالي',
    maritalStatus: 'الحالة الاجتماعية',
    single: 'أعزب',
    married: 'متزوج',
    divorced: 'مطلق',
    widowed: 'أرمل',
    dependents: 'عدد أفراد الأسرة المعالين',
    employmentStatus: 'الحالة الوظيفية',
    employed: 'يعمل',
    unemployed: 'لا يعمل',
    selfEmployed: 'أعمال حرة',
    retired: 'متقاعد',
    monthlyIncome: 'إجمالي الدخل الشهري',
    housingStatus: 'نوع السكن',
    owned: 'ملك',
    rented: 'مستأجر',
    withFamily: 'مع العائلة',
    
    // Step 3
    situationDescriptions: 'وصف الحالة',
    situationDescriptionsFull: 'تفاصيل الوضع والاحتياجات',
    currentSituation: 'الوضع المالي الحالي',
    currentSituationPlaceholder: 'يرجى وصف وضعكم المالي الحالي والظروف التي تستدعي طلب المساعدة...',
    employmentCircumstances: 'الظروف الوظيفية',
    employmentCircumstancesPlaceholder: 'يرجى توضيح وضعكم الوظيفي الحالي وأي صعوبات تواجهونها...',
    reasonForApplying: 'أسباب طلب الدعم',
    reasonForApplyingPlaceholder: 'يرجى توضيح الأسباب التي دعتكم لطلب الدعم الاجتماعي...',
    
    // Step 4
    reviewAndSubmit: 'مراجعة وإرسال',
    reviewAndSubmitFull: 'مراجعة الطلب وتقديمه',
    reviewYourInfo: 'يرجى مراجعة بياناتكم بعناية قبل تقديم الطلب',
    readyToSubmit: 'هل أنتم مستعدون لتقديم الطلب؟',
    submitWarning: 'يرجى التأكد من صحة جميع البيانات المدخلة حيث لا يمكن تعديلها بعد التقديم.',
    submitApplication: 'تقديم الطلب',

    // Email submission phases
    submittingApplication: 'جاري تقديم الطلب',
    processingInfo: 'جاري معالجة بياناتكم...',
    sendingConfirmation: 'جاري إرسال التأكيد',
    sendingToEmail: 'جاري إرسال التأكيد إلى بريدكم الإلكتروني...',
    emailSentSuccess: 'تم إرسال رسالة التأكيد بنجاح',
    confirmationSent: 'تم إرسال التأكيد إلى البريد الوارد',
    applicationSubmittedSuccess: 'تم تقديم الطلب بنجاح',
    applicationSuccessDesc: 'ستتلقون رسالة تأكيد بالبريد الإلكتروني تتضمن الخطوات التالية ومعلومات التواصل.',
    sendingTo: 'الإرسال إلى:',

    // Onboarding tour
    tourWelcomeTitle: 'مرحباً ببوابة الدعم الاجتماعي',
    tourWelcomeDesc: 'دعنا نرشدك خلال عملية التقديم. الأمر لا يستغرق سوى دقائق قليلة!',
    tourPersonalTitle: 'المعلومات الشخصية',
    tourPersonalDesc: 'أولاً، سنجمع معلوماتك الأساسية مثل الاسم والهوية وتفاصيل الاتصال. جميع المعلومات محفوظة بسرية وأمان.',
    tourPersonalTip1: 'احضر الهوية الوطنية',
    tourPersonalTip2: 'تأكد من صحة معلومات الاتصال',
    tourPersonalTip3: 'راجع عنوان البريد الإلكتروني',
    tourFamilyTitle: 'تفاصيل الأسرة والمالية',
    tourFamilyDesc: 'بعد ذلك، سنسأل عن وضع أسرتك والحالة المالية لفهم احتياجاتك بشكل أفضل.',
    tourFamilyTip1: 'اعرف دخلك الشهري',
    tourFamilyTip2: 'احسب جميع المعالين',
    tourFamilyTip3: 'أضف جميع مصادر الدعم',
    tourSituationTitle: 'حالتك',
    tourSituationDesc: 'هنا ستصف حالتك الحالية وسبب التقديم. كن مفصلاً وصادقاً - هذا يساعدنا على خدمتك بشكل أفضل.',
    tourSituationTip1: 'كن محدداً حول تحدياتك',
    tourSituationTip2: 'اشرح وضعك الوظيفي',
    tourSituationTip3: 'استخدم مساعد الذكاء الاصطناعي للمساعدة في الكتابة',
    tourReviewTitle: 'مراجعة وإرسال',
    tourReviewDesc: 'أخيراً، ستراجع جميع معلوماتك قبل الإرسال. يمكنك تعديل أي قسم إذا لزم الأمر.',
    tourReviewTip1: 'راجع كل شيء بعناية',
    tourReviewTip2: 'عدل أي أخطاء قبل الإرسال',
    tourReviewTip3: 'احفظ رقم طلبك',
    tourReadyTitle: 'أنت جاهز!',
    tourReadyDesc: 'تعرف الآن كل ما تحتاجه لإكمال طلبك. حظاً موفقاً!',
    quickTips: 'نصائح سريعة',
    skipTour: 'تخطي الجولة',
    startApplication: 'بدء الطلب',

    // App Details Page
    caseStudy: ' دراسة الحالة',
    caseStudyFor: 'دراسة حالة التنفيذ لـ',
    caseStudyDocumentation: 'للتطبيق',
    northbaySolutions: 'Northbay Solutions',
    appDetailsTitle: 'منصة الدعم الاجتماعي الذكية',
    appDetailsSubtitle: 'منصة حكومية متطورة تتيح تقديم طلبات الدعم الاجتماعي بسهولة مع مساعد ذكي للكتابة ودعم كامل للغتين العربية والإنجليزية.',
    viewApp: 'تصفح المنصة',
    viewCode: 'عرض الكود البرمجي',
    requirementsFulfilled: 'المتطلبات التي تمت',
    requirementsFulfilledDesc: 'تم تنفيذ جميع المتطلبات المطلوبة في دراسة الحالة مع إضافات وتحسينات متقدمة.',

    reqMultiStep: 'نموذج تقديم متدرج من 4 خطوات',
    reqMultiStepDesc: 'تم تطوير النموذج من 3 خطوات إلى 4 خطوات مع إمكانية المراجعة والتعديل السهل قبل التقديم',
    reqAI: 'تقنية الذكاء الاصطناعي المتقدمة',
    reqAIDesc: 'مساعد ذكي لصياغة النصوص وتحسين محتوى الطلبات',
    reqResponsive: 'تصميم متوافق مع جميع الأجهزة',
    reqResponsiveDesc: 'واجهة متجاوبة تدعم الهواتف الذكية والأجهزة اللوحية وأجهزة سطح المكتب',
    reqAccessibility: 'إمكانية الوصول الشامل',
    reqAccessibilityDesc: 'متوافق مع معايير الوصول العالمية ويدعم قارئات الشاشة والتنقل بلوحة المفاتيح',
    enhanced: 'محسّن',

    keyFeatures: 'الخدمات والمزايا الرئيسية',
    keyFeaturesDesc: 'مجموعة شاملة من الخدمات التي تجعل عملية تقديم الطلبات سهلة وميسرة.',
    featureAI: 'المساعد الذكي للكتابة',
    featureAIDesc: 'تقنية ذكية تساعد في صياغة الطلبات بشكل مهني ومناسب',
    featureProgress: 'متابعة حالة الطلب',
    featureProgressDesc: 'نظام مرئي لمتابعة مراحل تقديم الطلب مع إمكانية الانتقال بين الخطوات',
    featureBilingual: 'الدعم الكامل للغتين',
    featureBilingualDesc: 'منصة متكاملة باللغتين العربية والإنجليزية مع تخطيط مناسب لكلا الاتجاهين',
    featureAutoSave: 'الحفظ التلقائي للبيانات',
    featureAutoSaveDesc: 'حفظ تلقائي لبيانات الطلب لضمان عدم فقدانها أثناء التصفح',
    featureEmail: 'تأكيد استلام الطلب',
    featureEmailDesc: 'نظام تأكيد احترافي عبر البريد الإلكتروني لضمان وصول الطلب',
    featureOnboarding: 'دليل الاستخدام التفاعلي',
    featureOnboardingDesc: 'جولة إرشادية شاملة تشرح كيفية استخدام المنصة للمستخدمين الجدد',

    technicalExcellence: 'المعايير التقنية المتقدمة',
    technicalExcellenceDesc: 'تم تطوير المنصة باستخدام أحدث التقنيات وأفضل الممارسات العالمية لضمان الموثوقية والأداء العالي.',
    modernTechStack: 'التقنيات الحديثة المستخدمة',
    qualityAssurance: 'ضمان الجودة والاختبار',
    comprehensiveTesting: 'اختبارات شاملة تغطي 17 حالة مختلفة',
    accessibilityCompliance: 'متوافق مع المعايير العالمية للوصول',
    performanceOptimized: 'محسّن للأداء العالي',
    securityFirst: 'الأمان والخصوصية أولاً',

    projectStructure: 'الهيكل التقني للمنصة',
    projectStructureDesc: 'عرض مرئي شامل يوضح بنية النظام وتنظيم مكونات المنصة التقنية.',
    projectStructureDiagram: 'مخطط الهيكل التقني',
    beyondRequirements: 'الخدمات الإضافية المتقدمة',
    beyondRequirementsDesc: 'مزايا وخدمات إضافية تعزز من تجربة المستفيدين وتظهر الجودة العالية للمنصة.',
    bonusOnboarding: 'نظام الإرشاد التفاعلي للمستخدمين الجدد',
    bonusEmail: 'نظام تأكيد متطور عبر البريد الإلكتروني بمراحل متعددة',
    bonusCelebration: 'تأثيرات بصرية تفاعلية للتأكيد الإيجابي',
    bonusTheme: 'تصميم احترافي متكامل',
    bonusRTL: 'دعم كامل للتخطيط العربي من اليمين إلى اليسار',
    bonusTesting: 'مجموعة اختبارات شاملة لضمان جودة النظام',

    readyToExplore: 'هل أنتم مستعدون لتجربة المنصة؟',
    readyToExploreDesc: 'اكتشفوا جميع الخدمات والمزايا المتاحة في المنصة أو تصفحوا الكود البرمجي للاطلاع على تفاصيل التطوير.',
    tryApplication: 'تجربة المنصة',
    viewSource: 'الاطلاع على الكود البرمجي',
    builtWith: 'تم التطوير بإتقان وعناية لفريق',
    forAccessibleGovernment: 'Northbay Solutions',
  }
};

export const LanguageProvider = ({ children, lang }) => {
  const language = lang || 'en';

  const t = (key) => {
    if (!translations[language]) {
      console.warn(`Language ${language} not found, falling back to 'en'`);
      return translations['en'][key] || key;
    }
    return translations[language][key] || key;
  };

  const value = {
    language,
    t,
    isRTL: language === 'ar'
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};